### ISSUE TITLE
Ability Inputs Not working when playing as client net mode

### ISSUE THREAD

**Issue by aTylerRice** [Ciberusps/unreal-helper-library#21]
Hi firstly thanks for the great plugin and so far it works very well, but there's a big issue that I have so far that I haven't been able to solve.

I have the ability system component on my player state:

`AGamePlayerState::AGamePlayerState(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	
	AbilitySystemComponent = ObjectInitializer.CreateDefaultSubobject<UChromaAbilitySystemComponent>(this, TEXT("AbilitySystemComponent"));
	AbilitySystemComponent->SetIsReplicated(true);
	AbilitySystemComponent->SetReplicationMode(EGameplayEffectReplicationMode::Mixed);

	AttributeSet = CreateDefaultSubobject<UGameCharacterBaseAttributeSet>(TEXT("AttributeSet"));
	
}

void AGamePlayerState::BeginPlay()
{
	Super::BeginPlay();

	// Initialize the AttributeSet
	if (AbilitySystemComponent && AttributeSet)
	{
		AttributeSet->InitializeAttributes();
		AbilitySystemComponent->InitStats(UGameCharacterBaseAttributeSet::StaticClass(), nullptr);
	}
}`

and I have this in my character possessed by:
`
void AGameCharacter::PossessedBy(AController* NewController)
{
	Super::PossessedBy(NewController);

	GetAbilitySystemComponent()->InitAbilitySystem(NewController, this);
`

The attribute set is applied as I can see with showdebug abilitysystem but actually this showdebug ability system looks the same in standalone listen server and client net modes. The Input works on listen server and standalone but not for client net mode.

What am I doing wrong with this?

Could using the ability system component on player state be added to the docs which would be helpful to me and maybe many others?

**Comment by Ciberusps** [comment]
Hi, tbh didn't tested with network much, will try to check on weekend whats going wrong

**Comment by aTylerRice** [comment]
I'll report back if I find something before then. Still trying to debug this. Getting much more familiar with this code base though. Thanks again!

**Comment by aTylerRice** [comment]
actually just found the issue. 

```
void AUHLPlayerController::OnPossess(APawn* InPawn)
{
    Super::OnPossess(InPawn);

    CachedPlayerCharacter = Cast<AUHLPlayerCharacter>(InPawn);
}

void AUHLPlayerController::PostProcessInput(const float DeltaTime, const bool bGamePaused)
{
    Super::PostProcessInput(DeltaTime, bGamePaused);

    if (!CachedPlayerCharacter.IsValid()) return;

    if (UUHLAbilitySystemComponent* ASC = CachedPlayerCharacter.Get()->GetUHLAbilitySystemComponent())
    {
        ASC->ProcessAbilityInput(DeltaTime, bGamePaused);
    }
}
```


The CachedPlayerCharacter here is always null when running as client. I couldn't really fix this and leave it the same so I did this to fix it:

```
void AMyGamePlayerController::PostProcessInput(const float DeltaTime, const bool bGamePaused)
{
	Super::PostProcessInput(DeltaTime, bGamePaused);

	if(AMyGamePlayerState* PS = GetPlayerState<AMyGamePlayerState>())
	{
			if (UMyGameAbilitySystemComponent* ASC = PS->GetMyGameAbilitySystemComponent())
			{
				ASC->ProcessAbilityInput(DeltaTime, bGamePaused);
			}
	}
}
```

This now works! Thanks so much!

**Comment by Ciberusps** [comment]
> Could using the ability system component on player state be added to the docs which would be helpful to me and maybe many others?

Btw I forgot, added to backlog will add docs
