### ISSUE TITLE
InRange Distance calculation error

### ISSUE THREAD

**Issue by nozomanai** [Ciberusps/unreal-helper-library#5]
At the beginning of the game, the distance between NPCs and players is correct.
When the NPC stops moving and moves again, the distance is incorrect.
Suspected distance calculation error after running the inRange node for the second time

beginPlay Distance is correct
![111](https://github.com/user-attachments/assets/b7e0125b-e920-4f9c-9716-62745593b2b4)

Not the first time running in range，In such close proximity, the distance is over 1000
![2222](https://github.com/user-attachments/assets/9ccc780c-a2db-491d-ab00-a3325f3579db)

AI config
![333](https://github.com/user-attachments/assets/e6e3f68b-033f-46ed-9422-3b94d62cbef3)

**Comment by Ciberusps** [comment]
yep found how to reproduce it, created additional test in a `Gym_AI`(`Plugins/UnrealHelperLibrary/Content/Gyms/Gym_AI`) 
Hope I'll fix tomorrow

**Comment by Ciberusps** [comment]
Here "SelfActor" is AIController, thats why distance is wrong, I'll be at home in 4-5h and will fix
![image](https://github.com/user-attachments/assets/a2b2aa07-21e8-4ce7-b961-f38be8717a57)

**Comment by Ciberusps** [comment]
fixed in https://github.com/Ciberusps/unreal-helper-library/commit/b195f4d04ea02341960ce6e73f60f0334e773766
